include("${LUMEX_SOURCE_DIR}/lumex/tests/cmake/setup_all_on.cmake")
set(LUMEX_BUILD_UTILITY OFF)
# Every module that requires utility and is checked before contracts is off,
# so that contracts is the one that fails.
set(LUMEX_BUILD_CIRCULAR_BUFFER OFF)
set(LUMEX_BUILD_EXPECTED OFF)
set(LUMEX_BUILD_BASE64 OFF)
set(LUMEX_BUILD_CRC OFF)
set(LUMEX_BUILD_ENVIRONMENT OFF)
set(LUMEX_BUILD_TIME OFF)
set(LUMEX_BUILD_FILESYSTEM OFF)
set(LUMEX_BUILD_STRING_VIEW OFF)
set(LUMEX_BUILD_FMT OFF)
set(LUMEX_BUILD_REFLECTION OFF)
set(LUMEX_BUILD_SERIAL OFF)
set(LUMEX_BUILD_UNICODE OFF)
set(LUMEX_BUILD_XML OFF)
set(LUMEX_BUILD_TEMPORARY OFF)
set(LUMEX_BUILD_EXCEPTIONS OFF)
set(LUMEX_BUILD_LOGGING OFF)
set(LUMEX_BUILD_HARDWARE OFF)
set(LUMEX_BUILD_RESOURCE_MONITOR OFF)
set(LUMEX_BUILD_SETTINGS OFF)
set(LUMEX_BUILD_JSON OFF)
set(LUMEX_BUILD_HAZARD_POINTER OFF)
include("${LUMEX_SOURCE_DIR}/cmake/LumexModules.cmake")
lumex_check_module_dependencies()
message(FATAL_ERROR "expected lumex_check_module_dependencies to stop")
