include("${LUMEX_SOURCE_DIR}/lumex/tests/cmake/setup_all_on.cmake")
include("${LUMEX_SOURCE_DIR}/cmake/LumexModules.cmake")

set(LUMEX_BUILD_APPLIED OFF)
set(LUMEX_BUILD_XML OFF)
foreach(_opt
        LUMEX_BUILD_ATOMIC LUMEX_BUILD_BASE64 LUMEX_BUILD_CIRCULAR_BUFFER LUMEX_BUILD_CRC
        LUMEX_BUILD_ENVIRONMENT LUMEX_BUILD_EXCEPTIONS LUMEX_BUILD_EXPECTED
        LUMEX_BUILD_FILESYSTEM LUMEX_BUILD_GENERATORS LUMEX_BUILD_OPTIONAL
        LUMEX_BUILD_REFLECTION LUMEX_BUILD_STRING LUMEX_BUILD_STRING_VIEW LUMEX_BUILD_FMT
        LUMEX_BUILD_TEMPORARY LUMEX_BUILD_TIME LUMEX_BUILD_UNICODE)
    set(${_opt} OFF)
endforeach()
set(LUMEX_BUILD_MATH ON)
set(LUMEX_BUILD_UTILITY ON)
set(LUMEX_BUILD_CORE ON)

lumex_check_module_dependencies()
